#!/usr/bin/env bash

rm -rf /tmp/release
mkdir -p /tmp/release
cp "pod-babashka-$POD_DB_TYPE" /tmp/release

VERSION=$(cat resources/POD_BABASHKA_SQL_VERSION)

cd /tmp/release

arch=${BABASHKA_ARCH:-amd64}

## release binary as zip archive
archive="pod-babashka-$POD_DB_TYPE-$VERSION-$BABASHKA_PLATFORM-$arch.zip"
zip "$archive" "pod-babashka-$POD_DB_TYPE"

## cleanup
cd -

pwd

./bb release-artifact "/tmp/release/$archive"

cd /tmp/release
rm "pod-babashka-$POD_DB_TYPE"
