#!/usr/bin/env bash

rm -rf /tmp/release
mkdir -p /tmp/release
cp "pod-babashka-$POD_DB_NAME" /tmp/release

VERSION=$(cat resources/POD_BABASHKA_SQL_VERSION)

cd /tmp/release

## release binary as zip archive

zip "pod-babashka-$POD_DB_NAME-$VERSION-$BABASHKA_PLATFORM-amd64.zip" "pod-babashka-$POD_DB_NAME"

## cleanup

rm "pod-babashka-$POD_DB_NAME"
