#!/usr/bin/env bash

if [ "$BABASHKA_PLATFORM" = "macos" ]
then
    if [ "$POD_DB_TYPE" = "mysql" ]
    then
        echo "Skipping tests due to ssl error in test setup"
        exit 0
    fi
fi

set -euo pipefail

if [ "$POD_DB_TYPE" = "postgresql" ]
then
    clojure -M:test:postgresql -n pod.babashka.postgresql-test
fi

if [ "$POD_DB_TYPE" = "hsqldb" ]
then
    clojure -M:test -n pod.babashka.hsqldb-test
fi

if [ "$POD_DB_TYPE" = "mysql" ]
then
    clojure -M:test:mysql -n pod.babashka.mysql-test
fi

if [ "$POD_DB_TYPE" = "oracle" ]
then
    clojure -M:test:oracle -n pod.babashka.oracle-test
fi

if [ "$POD_DB_TYPE" = "mssql" ]
then
    clojure -M:test:mssql -n pod.babashka.mssql-test
fi

if [ "$POD_DB_TYPE" = "duckdb" ]
then
    clojure -M:test:duckdb -n pod.babashka.duckdb-test
fi