#!/usr/bin/env bash

if [ "$POD_DB_NAME" = "postgresql" ]
then
    clojure -A:test -n pod.babashka.postgresql-test
fi

if [ "$POD_DB_NAME" = "hsqldb" ]
then
    clojure -A:test -n pod.babashka.hsqldb-test
fi
